version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3002:80"
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmeeting
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 